### ISSUE TITLE
User Story: As a site user, I can create a new recipe so that I can share it with other users.

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#1]
EPIC: Recipe Creation

As a **user** I can **create a new recipe** so that **I can share it with other users.**

**Acceptance Criteria**

- Recipe form has a title, description, category, image and ingredients
- The user can add as many ingredients as needed
- The user can preview the recipe before submitting it
- After submitting the recipe, the user is redirected to the recipe detail page
- if the user tries to create a recipe without being logged in, they are redirected to the login page.

**Tasks**

- [ ] Task 1: Design and implement a new recipe item.
- [ ] Task 2: Implement recipe upload functionality
- [ ] Task 3: Add recipe validation and error handling
- [x] Task 4: Test recipe creation functionality
