### ISSUE TITLE
User Story: Pagination. Epic: #22

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#11]
As a **user** I can **view a paginated list of memes** so that **I can easily see memes at a glance**

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that I am a user on a desktop computer **When** viewing memes **Then** I can see six meme cards on one page.
- Acceptance Criteria 2 
  - **Given** that I am a site user **When** I am viewing the memes page **Then** I am provided with an option to reorder memes by most liked or date uploaded.

**Tasks**
- [x] Create functionality to paginate memes.
- [x] Create four meme cards per page.
- [x] Make pagination so it only shows 5-10 closest pages but is still accessible with the next or previous buttons.

**Epic: #22**
