### ISSUE TITLE
User Story: Update user account. Epic: #18

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#26]
As a **logged-in user** I can **edit my account** so that **update my detail and profile picture**

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that I am currently logged-in user **When** going on my own profile **Then** I can edit my details
- Acceptance Criteria 1 
  - **Given** that I am currently logged-in user **When** going on my own profile **Then** I can change my profile photo
- Acceptance Criteria 1 
  - **Given** that I am currently logged-in user **When** going on my own profile **Then** I can see all my uploaded memes

**Tasks**
- [ ] Create functionality for a user to update their own personal information.
- [ ] Add functionality to change profile photo.
- [ ] Add an option for a user to view, edit and delete all their uploaded memes.

**Epic: #18**
