### ISSUE TITLE
User Story: Delete current user. Epic: #18

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#27]
As a **logged-in user** I can **delete my account** so that **I can easily delete my account and all my uploaded memes in one action**

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that I am currently a logged-in user **When** going on my own profile **Then** I can easily delete my own account.
- Acceptance Criteria 1 
  - **Given** that I am currently a logged-in user **When** deleting my account **Then** all my memes are deleted also.

**Tasks**
- [ ] Create functionality for users to be able to delete their own accounts.
- [ ] Make sure when a user deletes their account all memes for that user are deleted also.
- [ ] Ask for user confirmation before the account is deleted.
- [ ] Add a success message after the operation is completed.

**Epic: #18**
