### ISSUE TITLE
User Story: User account login/logout. Epic: #8

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#28]
As a **user** I can **login/logout of my account** so that **only I can make changes to my account**

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that I am a registered user **When** I open the website **Then** Login button is clearly visible on the navigation bar.
- Acceptance Criteria 1 
  - **Given** that I am a registered user who is not signed in **When** I try to comment on a meme  **Then** I am prompted to log in.
- Acceptance Criteria 1 
  - **Given** that I am a currently logged-in user **When** I am on any page on the website **Then** a clear Logout button is displayed on the navigation bar.

**Tasks**
- [ ] Add functionality for a user to be able to log in/log out from the navigation bar.
- [ ] Use the Django Allauth package to manage validations.
- [ ] Add flash messages to confirm to the user if the action was successful or not.

**Epic: #8**
