### ISSUE TITLE
User Story: Set-up vsCode

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#3]
As a **developer** I can **use local IDE** so that **I can start developing my program**

**Acceptance Criteria**
- Acceptance Criteria 1 - Connect the vsCode and set up with the project.
- Acceptance Criteria 1 - The vsCode should only install packages needed for this project.

**Tasks**
- [ ] Task 1 - Clone repository from GitHub to vsCode.
- [ ] Task 2 - Create a virtual environment to install only project-related packages.
- [ ] Task 3 - Install Django.

**Epic: #2 **
