### ISSUE TITLE
User Story: Report a meme. Epic: #20

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#32]
As a **authenticated user** I can **report a meme to the administrator** so that **it can be removed in case of inappropriate content**

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that I am authenticated user **When** I see a meme with inappropriate content **Then** I can report it to the website administrator.
- Acceptance Criteria 1 **Given** that **When** the **Then**
- Acceptance Criteria 1 **Given** that **When** the **Then**

**Tasks**
- [ ] On a single meme page create a link to report a meme.
- [ ] Create an email notification for the administrator if a user reports a meme.
- [ ] Add user action confirmation flash message.

**Epic: #20**
