### ISSUE TITLE
User Story: Hide secret keys/variables.

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#4]
As a **developer,** I can **hide all secret keys and variables** so that **when uploading to GitHub, the site will be secure**

**Acceptance Criteria**

- Acceptance Criteria 1 - Create an env.py file to store all sensitive information.

**Tasks**

- [ ] Task 1 - Create an env.py file and add it to the .gitignore file.
- [ ] Task 2 - Import os in env.py and settings.py file.
- [ ] Task 3 - Move all sensitive data to the env.py file and connect it with settings.py
- [ ] Task 4 - Upload the project to GitHub

**Epic: #2**
