### ISSUE TITLE
User Story: Initial deployment to Heroku

### ISSUE THREAD

**Issue by Inc21** [Inc21/TechieMeme-PP4#5]
As a **developer,** I can **deploy the website skeleton to Heroku** so that **I can make sure all initial settings are correct**

**Acceptance Criteria**
- Acceptance Criteria 1 - The project needs to be set up with all the correct settings and files,
- Acceptance Criteria 1 - Has to be connected to GitHub for easy deployment.

**Tasks**
- [ ] Task 1 - Create Procfile as per Heroku instructions.
- [ ] Task 2 - Create requirements.txt file.
- [ ] Task 3 - Add config vars in Heroku project settings.

**Epic: #2**
